### PR TITLE
configure ci

### PR DESCRIPTION
**Pull request by raul-gracia**
## Description
This will configure all realted github actions and workflows:
- Enable a workflow for running all test checks: rspec, rubocop, brakeman, code coverage, etc
- Enable a workflow to automatically deploy to Heroku ( temporary)
- Add a Pull Request template
- Add code owners file to automatically assign prs to ourselves

## Trello Card Link

https://trello.com/c/jSWbNEm9

### CODE REVIEW

**Comment by raul-gracia** [comment]
[Enable all the github actions plugins for the repo](https://trello.com/c/jSWbNEm9/8-enable-all-the-github-actions-plugins-for-the-repo)

**Comment by raul-gracia** [comment]
At the moment the 2 checks are failing for different reasons:
- the rspec one is an error that has something to do with webpack and the favicon. Something that might get fixed after we merged to the main branch where some of the other fixes have been made.
- the rubocop one needs all the configurations changes made on PR #7 to pass

**Comment by raul-gracia** [comment]
[add simple coverage for code coverage](https://trello.com/c/1pUfoicm/16-add-simple-coverage-for-code-coverage)

**Comment by padv2010** [comment]
@raul-gracia this PR has some conflicts, so worth rebasing with `main` and check if the build is green? `main` branch is green for me.

**Comment by raul-gracia** [comment]
@padv2010 all conflicts are fixed now

**Comment by padv2010** [comment]
Thanks @raul-gracia 
Any chance of having a cleaner commit history? We have two merges from master to this branch, and the commits are not telling an incremental story of changes. There are quite [a few guidelines that can help to align us to GDS standards](https://gds-way.cloudapps.digital/standards/source-code/working-with-git.html#atomic-commits). One of the comments, for example, is to start commits with capital letter :)

Thoughts?

**Comment by raul-gracia** [comment]
There already was another merge commit from the PR before on the history done by Abi, I looks like she might have been just committing on the main branch directly, which makes sense when you're working on the project alone.
Github has 3 different strategies when merging a PR:
- Create a merge commit
- Squash and merge
- Rebase and merge
Which ever strategy you think is best, we can use, or even set as default and enforce via repository settings.

**Comment by padv2010** [comment]
@raul-gracia I don't I have explained myself. What I mean, is instead of merging the main branch `into` the branch (as it happened twice on this PR), we can just rebase the current work on top. Also, trying to have commits that tell a story, make the review easier and tracking changes through time much easier as well.
When it comes to the three approaches, they are all compatible with the feedback I tried to give.

**Comment by padv2010** [comment]
@raul-gracia I am merging this PR, as there is no value in blocking more time.

**Pull request merged**
