### PR TITLE
Show validation error on the date_of_birth attribute

### PR DESCRIPTION
**Pull request by padv2010**
Depends on #33 to fix issues with `nil` years or dates that are partially empty

## Trello Card Link

https://trello.com/c/gIQaRF2K/62-application-form-date-of-birth

## Description

Adds day, month, year validation for the `birth day` of the applicant.  The validation will 
make sure that all the fields are present and that the date is valid.

## Technical notes

1. I have reused the `DayMonthYearDateValidator` introduced in #31
2. I have introduced [duplication on the validation](https://github.com/DFE-Digital/international-teacher-relocation-payment/commit/cbb6246d556015f958ed2be81029324ac6ba129d); I have not 
extracted out the duplicated code as I would like to have a simple PR so this story 
can be properly tested. But I will proceed next with the refactoring.

### Next steps

1. Remove duplication between `start_date_contract` and `entry_date`
2. Unify questions in #33 #31 for dates with a single class that will remove duplication. 

## Screenshots

image

image

### CODE REVIEW

**Comment by padv2010** [comment]
[Application form: date of birth](https://trello.com/c/gIQaRF2K/62-application-form-date-of-birth)

**Comment by raul-gracia** [comment]
Wouldn't it be easier to validate dates just using the `Date.parse()` method? and just return the error if anything goes wrong? 
`Date.parse("#{day}/#{month}/#{year}")`

That will handle all cases, illegal dates, empty ones, using characters instead of numbers... etc

**Comment by padv2010** [comment]
> Wouldn't it be easier to validate dates just using the Date.parse() method? and just return the error if anything goes wrong?
> Date.parse("#{day}/#{month}/#{year}")
> That will handle all cases, illegal dates, empty ones, using characters instead of numbers... etc

Thanks for the review @raul-gracia 

@raul, if you question is about using Date.parse() instead of Date.new [as in this code](https://github.com/DFE-Digital/international-teacher-relocation-payment/pull/36/files#diff-7b27f710060e40aca93235f43d1dfac1c44583a086ac22e350afb9ef7ac825caR28-R36), no problem. I would rather using `Date.valid_date?` because it does not locale dependent. `Date.parse` depends on date format. 

Do you want me to do the change?

For next time, can you please add the comment linked to the code that you are commenting about? It will get easier to discuss there?

**Comment by raul-gracia** [comment]
Yes, I meant that part of the code uses `Date.new`. 
Yes, `Date.parse` depends on the format and the locale, but the locale and the timezone are being setup in the Rails Application Configuration, and this is an app running in the UK for the UK government, so it should be safe to assume dates will follow the UK format, and we have a clear distinction of day, month and year from the parameters anyway. Also, I find it simpler to just catch the `invalid date (Date::Error)` from `Date.parse()` and just add an error for the date attribute, than using the `InvalidDate` struct which is, in my opinion, not necessary.

**Comment by padv2010** [comment]
Ok, I got you now. Thanks for explaining.

The `InvalidDate` class is needed, we cannot get rid of it regardless on how we do the validation. Those are different concerns.

`InvalidDate` was first done by Abigail and it was a good way to integrate the ActiveModel lifecycle for validations with the GOV.UK component that presents dates. By encapsulating the errored date with a class we dry-up completely all the edge cases and errors at the presentation level because we need to wrap the three fields (day, month, year) in a single attribute so errors are presented properly on the UI.

When it comes to the validation, I would prefer not to depend on the `Locale` if I can avoid it. If you prefer me to use `Date.is_valid?(day, month, year)` instead of `Date.new(day, month, year)` I am fine, no problem. But creating a string manually that depends on the locale to be parsed in order to validate it is not a good fit for me. Seems like a dependency that we don't really need and I can't see the benefit, to be honest.

If you find a way to get rid of the `InvalidDate` then feel free to create a PR for it. I would love to learn a better way to handle it.

On my next PR, I will be unifying how dates are being created, but first I would need to merge this and #33 and #31.

**Comment by raul-gracia** [comment]
It's ok then, you can use `Date.new` with the `InvalidDate` class. I'll rather move forward with the delivery than get hanged up on small details.

**Review by raul-gracia — APPROVED** [review]

**Pull request merged**
